[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \\.git
  | \\.hg
  | \\.mypy_cache
  | \\.tox
  | \\.venv
  | \\.idea
  | \\iPhyloGeo_env
  | _build
  | buck-out
  | build
  | dist
)/
'''
