[tool.ruff]
line-length = 150
select = ["E", "F", "W", "C", "N", "B", "Q", "A"]
ignore = [
    "E501",  # Ignore line length errors
    "F401",  # Ignore unused imports
    "N806",  # Ignore variable in function should be lowercase
    "N802",  # Ignore function name should be lowercase
    "B007",  # Ignore loop control variable not used within loop body
    "C901",  # Ignore function is too complex
    "C408",  # Ignore unnecessary `dict` call
]
target-version = "py39"

[tool.ruff.lint.per-file-ignores]
"**/event_connector.py" = ["N815"]

[tool.black]
line-length = 150
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \\.git
  | \\.hg
  | \\.mypy_cache
  | \\.tox
  | \\.venv
  | \\.idea
  | \\iPhyloGeo_env
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 150
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
