[tool.ruff]
line-length = 88
select = ["E", "F", "W", "C", "N", "B", "Q", "A"]
ignore = [
    "E501",  # Ignore line length errors
    "F401",  # Ignore unused imports
    "N806",  # Ignore variable in function should be lowercase
    "N802",  # Ignore function name should be lowercase
    "B007",  # Ignore loop control variable not used within loop body
    "C901",  # Ignore function is too complex
    "C408",  # Ignore unnecessary `dict` call
]
target-version = "py39"
