file_name: C:/Users/lolow/Desktop/.Toulouse/2023 2024/Stage/Projet/iPhyloGeo_plus_plus_0613/datasets/geo_with_loc.csv
data_names: [ALLSKY_SFC_SW_DWN, T2M, QV2M, PRECTOTCORR, WS10M]
reference_gene_dir: F:/STUDY/projects/PFE/aPhyloGeo_plus_plus/datasets
reference_gene_file: simplot.fasta
makeDebugFiles: false
bootstrap_amount: 100
specimen: id
names: [ID, ALLSKY_SFC_SW_DWN, T2M, QV2M, PRECTOTCORR, WS10M]
bootstrap_threshold: 40
dist_threshold: 60
distance_method: '1'
alignment_method: '1'
fit_method: '1'
tree_type: '1'
rate_similarity: 90
method_similarity: '5'
window_size: 20
step_size: 100
