file_name: F:/STUDY/projects/PFE/aPhyloGeo_plus_plus/datasets/simplot.csv
specimen: id
names: [id, ALLSKY_SFC_SW_DWN, T2M, QV2M, PRECTOTCORR, WS10M, LAT, LONG]
bootstrap_threshold: 555
dist_threshold: 0
window_size: 555
step_size: 555
bootstrap_amount: 555
data_names: [ALLSKY_SFC_SW_DWN, T2M, QV2M, PRECTOTCORR, WS10M, LAT, LONG]
reference_gene_dir: F:/STUDY/projects/PFE/aPhyloGeo_plus_plus/datasets
reference_gene_file: small_seq.fasta
makeDebugFiles: true
alignment_method: '1'
distance_method: '0'
fit_method: '1'
tree_type: '1'
rate_similarity: 555
method_similarity: '1'
