file_name: F:/STUDY/projects/PFE/aPhyloGeo_plus_plus/datasets/geo_with_loc.csv
specimen: fdfdsfdsf
names: [id, ALLSKY_SFC_SW_DWN, T2M, QV2M, PRECTOTCORR, WS10M, LAT, LONG]
bootstrap_threshold: 11
dist_threshold: 5
window_size: 50
step_size: 222
bootstrap_amount: 100
data_names: [ALLSKY_SFC_SW_DWN, T2M, QV2M, PRECTOTCORR, WS10M, LAT, LONG]
reference_gene_dir: F:/STUDY/projects/PFE/aPhyloGeo_plus_plus/datasets
reference_gene_file: small_seq.fasta
makeDebugFiles: false
alignment_method: '3'
distance_method: '0'
fit_method: '1'
tree_type: '1'
rate_similarity: 13
method_similarity: '1'
