file_name: F:/STUDY/projects/PFE/aPhyloGeo_plus_plus/datasets/h_pylori_small.csv
specimen: id
names: [species, temperature, precipitation, humidity, longitude, latitude]
bootstrap_threshold: 3
dist_threshold: 60
window_size: 99
step_size: 99
bootstrap_amount: 99
data_names: [temperature, precipitation, humidity, longitude, latitude]
reference_gene_dir: F:/STUDY/projects/PFE/aPhyloGeo_plus_plus/datasets
reference_gene_file: h_pylori_small.fasta
makeDebugFiles: true
alignment_method: '1'
distance_method: '0'
fit_method: '1'
tree_type: '1'
rate_similarity: 50
method_similarity: '1'
